name: Build flatpak

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      os: 
        default: "ubuntu-latest"
        type: string
      arch:
        default: "x86_64"
        type: string

jobs:
  build:
    name: Build bundle
    runs-on: ${{ inputs.os }}
    container:
      image: ghcr.io/andyholmes/flatter/kde:5.15-22.08
      options: --privileged

    steps:
      # Checkout a repository with Flatpak manifests
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: realthunder/org.freecadweb.FreeCAD.Link
          submodules: true

      - name: Setup build
        run: |
          tag=${{ inputs.ref }}
          name=org.freecadweb.FreeCAD.Link
          sed -i 's|branch: LinkMerge|tag: ${{ inputs.ref }}|' $name.yaml
          if ${{ endsWith(inputs.ref, 'stable') }}; then
            sed -i 's|asm3-daily|asm3|' $name.yaml
          fi
          url=https://github.com/realthunder/$name.BaseApp/releases/download/20230430/$name
          if ! which wget; then yum install wget -y; fi
          wget -q $url.BaseApp3.flatpak
          flatpak install -y $name.BaseApp3.flatpak
          rm $name.BaseApp3.flatpak
          df -h
          du -a / | sort -n -r | head -n 30

      - name: Build
        id: flatpak
        uses: andyholmes/flatter@main
        with:
          files: |
            org.freecadweb.FreeCAD.Link.yaml
          arch: ${{ inputs.arch }}
          upload-bundles: true
          cache-key: ''
          flatpak-builder-args: |
            --install-deps-from=flathub

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download assets
        uses: actions/download-artifact@v3

      - name: Prepare assets
        run: |
          set -x
          name=org.freecadweb.FreeCAD.Link
          mv $name*/*.flatpak .
          name=`echo *.flatpak`
          tag=${{ inputs.ref }}
          case $tag in
          *tip)
              echo "RELEASE_NAME=Tip" >> $GITHUB_ENV
              echo "IS_PRERELEASE=true" >> $GITHUB_ENV
              postfix=Tip_${tag%tip}
              ;;
          *edge)
              echo "RELEASE_NAME=Edge" >> $GITHUB_ENV
              echo "IS_PRERELEASE=true" >> $GITHUB_ENV
              postfix=Edge_${tag%edge}
              ;;
          *stable)
              echo "RELEASE_NAME=$tag" >> $GITHUB_ENV
              echo "IS_PRERELEASE=false" >> $GITHUB_ENV
              postfix=Stable_${tag%stable}
              ;;
          *)
              echo "Invalid tag"
              exit 1
          esac
          bundle_name=${name%.flatpak}.${postfix}.flatpak
          mv $name $bundle_name
          shasum -a 256 $bundle_name > $bundle_name-SHA256.txt
          echo 'RELEASE_ASSETS=*.flatpak*' >> $GITHUB_ENV

      - name: Delete old release assets
        uses: realthunder/delete-release-assets@v1
        with:
          fail-if-no-assets: false
          fail-if-no-release: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_NAME }}
          # repository: realthunder/FreeCAD
          assets: |
              ${{ env.RELEASE_ASSETS }}

      - name: Upload release
        uses: realthunder/action-gh-release@v1
        with:
          files: ${{ env.RELEASE_ASSETS }}
          name: ${{ env.RELEASE_NAME }}
          prerelease: ${{ env.IS_PRERELEASE }}
          tag_name: ${{ env.RELEASE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
